In [17]:
class Cookie:
    pass #함수


a = Cookie() #변수
b = Cookie()

In [18]:
class Calculator:
    def __init__(self): # __init__ -> 내장함수
        self.result = 0
        
    def add(self, num):
        self.result += num
        return self.result
    
    def sub(self, num):
        self.result -= num
        return self.result
    
    def sub(self, num):
        self.result *= num
        return self.result
    
cal1 = Calculator()
cal2 = Calculator() 
cal3 = Calculator()
print(cal1.add(3))
print(cal1.add(4))
print(cal2.add(4))
print(cal2.add(5))








3
7
4
9


In [19]:
class FourCal:
    def setdata(self,first,second): #밀어내는 함수
        self.first = first
        self.second = second
        
    def add(self): #더하는 함수
        result = self.first + self.second
        return result
    
    def sub(self): #빼는 함수
        result = self.first - self.second
        return result
    
    def mul(self): #곱하기
        result = self.first * self.second
        return result
    
    def div(self): #나누기
        result = self.first / self.second
        return result


# 클래스 선언 방법 1    
A = FourCal() # A라는 변수에 FourCal 클래스 선언
FourCal.setdata(A,4,5)  # FourCal 클래스에 setdata 함수 선언   ---> self : A , first : 4, second: 5

A.add() # A라는 변수에 add 함수 선언
A.sub() # A라는 변수에 sub 함수 선언
A.mul() # A라는 변수에 mul 함수 선언
A.div() # A라는 변수에 div 함수 선언

0.8

* 생성자


In [20]:
class FourCal:
    
    def __init__(self,first,second): #생성자 : 클래스의 인스턴스를 초기화하는 데 사용
        self.first = first
        self.second = second
        
    def setdata(self,first,second): #밀어내는 함수
        self.first = first
        self.second = second
        
    def add(self): #더하는 함수
        result = self.first + self.second
        return result
    
    def sub(self): #빼는 함수
        result = self.first - self.second
        return result
    
    def mul(self): #곱하기
        result = self.first * self.second
        return result
    
    def div(self): #나누기
        result = self.first / self.second
        return result


a = FourCal(3,4)
a.add()


7

In [21]:
a.sub()

-1

* 클래스의 상속

In [22]:
class MoreFourCal(FourCal): #MoreFourCal = 자식클래스, FourCal = 부모클래스 : 자식클래스가 부모클래스를 상속을 받는다. 기능이 같음.
    def pow(self):     #자식 클래스에서 제곱를 할 수 있는 함수만들었고 부모클래스에선 쓸 수 없음.
        result = self.first ** self.second
        return result

a = MoreFourCal(4,2)
a.pow()

16

In [23]:
a = MoreFourCal(4,2) #
a.pow()

16

* 메서드 오버라이딩

In [24]:
a = FourCal(4, 8)
a.div()

0.5

In [25]:
class SafeFourCal(FourCal):
    def div(self):
        if self.second == 0:
            return 0
        else:
            return self.first / self.second

        
a = SafeFourCal(4,0)
a.div()

0

* 클래스 변수

In [26]:
class Family:
    lastname = "김"

In [27]:
Family.lastname

a = Family() #a,b : 객체
b = Family()

a.lastname,b.lastname

('김', '김')

In [28]:
Family.lastname = "박"
a.lastname, b.lastname

('박', '박')

In [29]:
a.lastname = "최"
a.lastname

'최'

In [30]:
b.lastname

'박'

* 은행 업무

In [31]:
class CAccount:
    def __init__(self):
        self.result = 0
        
        
        
    def dispTitleMsg():
        print("홍길동 통장")
        print("------------------")
        print("1. 잔액확인")
        print("2. 입금")
        print("3. 출금")
        print("4. 종료")
        print("------------------")
    
    def bankTransaction(self):
        
        while True:
            A = int(input("메뉴를 선택해주세요. : "))
            if A == 1:
                print(f"잔액은 {self.result}입니다.")
                
            elif A == 2:
                deposit_amount = int(input("입금할 금액을 알려주세요. : "))
                if deposit_amount < 0:
                    print("정확한 금액을 말씀해주세요.")
                else:
                    self.deposit(deposit_amount)
                    print(f"{deposit_amount}원 입금 되었습니다. 잔액은 {self.result}원 입니다.")
              
            elif A == 3:
                withdraw_amount = int(input("출금할 금액을 알려주세요. : "))
                if withdraw_amount < 0:
                    print("정확한 금액을 말씀해주세요.")
                elif withdraw_amount > deposit_amount:
                    print("잔액이 부족합니다.")
                elif withdraw_amount == deposit_amount:
                    self.withdraw(withdraw_amount)
                    print(f"{withdraw_amount}원 출금 되었습니다. 잔액은 {self.result}원 입니다.")
                    
                else:
                    self.withdraw(withdraw_amount)
                    print(f"{withdraw_amount}원 출금 되었습니다. 잔액은 {self.result}원 입니다.")
                
            elif A == 4:
                print("계좌 거래가 종료 되었습니다.")
                break
            else:
                print("잘못 입력하셨습니다.")
            
     

    def deposit(self, amount):
            self.result += amount
            return self.result



    def withdraw(self, amount):
            self.result -= amount
            return self.result
    





B = CAccount()
CAccount.dispTitleMsg()
B.bankTransaction()


홍길동 통장
------------------
1. 잔액확인
2. 입금
3. 출금
4. 종료
------------------


ValueError: invalid literal for int() with base 10: ''

In [ ]:
class CAccount:
    def __init__(self, owner, amount=0, password = '1111'):
        self.owner = owner
        self.balance = amount
        self.password = password
        self.message ="""
        ------------------
        1. 잔액확인
        2. 입금
        3. 출금
        4. 종료
        ------------------
        """
        
        self.dispTitleMsg()
        
    def bankTransaction(self): 
        inPass = input("계좌 비밀번호를 입력해 주세요.")            
        if inPass != self.password:
            self.dispPassErr()
            return
        
        inNum = int(input("메뉴를 선택해 주세요."))
        
        if inNum == 4:
            self.dispEndBanking()
            return
        
        if inNum == 1:
            self.dispBalance()
        elif inNum == 2:
            self.deposit()    
        elif inNum == 3:
            self.withdraw()   
        
    def deposit(self):
        inAmount = int(input("입금할 금액을 알려주세요."))                    
        if inAmount < 0:
            self.dispAmountErr()
        else:
            self.balance += inAmount
            self.dispDepositSucc(inAmount)
            self.dispBalance()
        
    def withdraw(self):
        inAmount = int(input("출금할 금액을 알려주세요."))      
        if inAmount < 0:
            self.dispAmountErr()
        elif self.balance < inAmount:            
            self.dispLackbalance()
        else:
            self.balance -= inAmount
            self.dispWithdrawSucc(inAmount)
            self.dispBalance()
    
    # Display message
    def dispTitleMsg(self):
        print("%s 통장" % self.owner)
        print(self.message) 
    
    def dispBalance(self):
        print("잔액은 %d 입니다." % self.balance)
    
    def dispAmountErr(self):
        print("정확한 금액을 입력해주세요.")
    
    def dispLackbalance(self):
        print("잔액부족, 거래가 거절되었습니다.")
        
    def dispDepositSucc(self, amount):        
        print(amount, "원이 성공적으로 입금되었습니다.")
        
    def dispWithdrawSucc(self, amount):
        print(amount, "원이 성공적으로 인출되었습니다.")
        
    def dispPassErr(self):
        print("%s님은 거래할 수 없습니다." % self.owner) 
        
    def dispEndBanking(self):
        print("은행 업무를 종료합니다.")

# Implementation
amounHong = CAccount("홍길동", 1000)
amounHong.bankTransaction()
        

In [ ]:
import numpy as np

list1 = [1,2,3]
arr1 = np.array(list1)
arr1

array([1, 2, 3])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
import pandas as pd


data = {'학번':range(2000,2010),
        '성적': [85,95,75,70,100,100,95,85,80,85]}
df = pd.DataFrame(data, columns=['성적','학번'])
df

성적    학번
0   85  2000
1   95  2001
2   75  2002
3   70  2003
4  100  2004
5  100  2005
6   95  2006
7   85  2007
8   80  2008
9   85  2009

In [ ]:
df = pd.DataFrame(data, columns=['성적','학번'])
df

성적    학번
0   85  2000
1   95  2001
2   75  2002
3   70  2003
4  100  2004
5  100  2005
6   95  2006
7   85  2007
8   80  2008
9   85  2009

In [ ]:
class Circle: # 원의 넓이를 구하는 클래스
    # 클래스 변수
    pi = 3.1416  #파이 값

    def __init__(self, radius):  # radius = 반지름
        self.radius = radius

    def calculate_area(self):
        return self.pi * (self.radius ** 2) # 파이 곱하기 반지름 *2

    @classmethod
    def set_pi(cls, new_pi): # 새로운 파이
        cls.pi = new_pi

# 객체 생성 및 클래스 메서드 호출
circle1 = Circle(5) # Circle(5) 클래스를 circle1 변수에 넣음
print(f"원의 넓이: {circle1.calculate_area()}") # circle1 변수에 calculate_area 함수 선언

# 클래스 변수 변경
Circle.set_pi(3.14) # circle 클래스에서 파이 값 변경
circle2 = Circle(7) # 반지름 7
print(f"원의 넓이: {circle2.calculate_area()}")


원의 넓이: 78.53999999999999
원의 넓이: 153.86


In [ ]:
class Vehicle:
    def __init__(self, make, model, year): #make:차량 브랜드, model : 모델, year : 년도
        self.make = make
        self.model = model
        self.year = year

    def display_info(self): # 디스플레이 해주는 함수
        print(f"{self.year} {self.make} {self.model}")

# Car 클래스가 Vehicle 클래스를 상속받음
class Car(Vehicle): # 상속받음
    def __init__(self, make, model, year, fuel): # 연료까지 생성
        super().__init__(make, model, year) # super().__init__()은 파이썬에서 클래스 상속 관계에서 부모 클래스의 __init__ 메서드를 호출하는 방법 
        self.fuel = fuel 

    def display_info(self):
        super().display_info()
        print(f"Fuel type: {self.fuel}")

# 객체 생성 및 사용
my_car = Car("Toyota", "Corolla", 2018, "Gasoline")
my_car.display_info()


2018 Toyota Corolla
Fuel type: Gasoline


In [99]:
class Animal:
    def __init__(self, name, sound):
        self.name = name
        self.sound = sound

    def make_sound(self):
        print(f"{self.name}은(는) {self.sound} 소리를 냅니다.")

class Dog(Animal):
    def __init__(self, name):
        super().__init__(name, "왈왈")

class Cat(Animal):
    def __init__(self, name):
        super().__init__(name, "야옹")

cat = Cat("이름")
dog = Dog("dlasd")

cat.make_sound()
dog.make_sound()

이름은(는) 야옹 소리를 냅니다.
dlasd은(는) 왈왈 소리를 냅니다.


In [ ]:
class Shape:
    def __init__(self, name):
        self.name = name
    def get_area(self):
        pass
class Circle(Shape):
    def __init__(self, name, radius):
        super().__init__(name)
        self.radius = radius
    def get_area(self):
        return 3.1415 * self.radius ** 2

In [102]:
import random

class Account:
    # class variable
    account_count = 0

    def __init__(self, name, balance):
        self.name = name
        self.balance = balance
        self.bank = "SC은행"

        num1 = random.randint(0, 999)
        num2 = random.randint(0, 99)
        num3 = random.randint(0, 999999)

        num1 = str(num1).zfill(3)      # 1 -> '1' -> '001'
        num2 = str(num2).zfill(2)      # 1 -> '1' -> '01'
        num3 = str(num3).zfill(6)      # 1 -> '1' -> '0000001'
        self.account_number = num1 + '-' + num2 + '-' + num3  # 001-01-000001

        Account.account_count += 1


kim = Account("김민수", 100)
print(Account.account_count)
lee = Account("이민수", 100)
print(Account.account_count)


1
2
