In [2]:
import tensorflow as tf

print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.15.0


In [3]:
mnist = tf.keras.datasets.mnist

(x_train,y_train), (x_test,y_test) = mnist.load_data()
# 정수에서 부동 소수점 숫자로 변환
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 1s 0us/step


In [11]:
x_train

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [7]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)), # 2차원의 이미지를 1차원으로 펼치는 작업
    tf.keras.layers.Dense(128,activation = 'relu'),
    tf.keras.layers.Dropout(0.2),                 # 오버피팅을 방지하기 위한 층, 훈련과정에서 무작위로 20%의 뉴런을 비활성화 
    tf.keras.layers.Dense(10,activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])



# categorical_crossentropy는 원-핫 인코딩 형식의 레이블을 사용할때 적합
# sparse_categorical_crossentropy는 정수 형태의 레이블을 사용할 때 사용 단순히 정수로 표현

In [9]:
# MNIST 데이터셋의 첫 번째 훈련 이미지에 대한 예측을 수행
predictions = model(x_train[:1]).numpy()
predictions

array([[0.0876618 , 0.04627873, 0.08470261, 0.08963584, 0.09716794,
        0.0754277 , 0.08194966, 0.11197266, 0.21089885, 0.11430427]],
      dtype=float32)

In [10]:
# 확률 변환
tf.nn.softmax(predictions).numpy()

array([[0.09868803, 0.09468737, 0.09839642, 0.09888304, 0.09963065,
        0.09748803, 0.09812592, 0.10111663, 0.11163121, 0.10135266]],
      dtype=float32)

In [19]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [13]:
loss_fn(y_train[:1],predictions).numpy() # 실제 레이블과 예측값과의 손실값

2.3280256

In [14]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [15]:
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
   1/1875 [..............................] - ETA: 6:19 - loss: 2.4101 - accuracy: 0.1250

/Users/choejong-gyu/anaconda3/lib/python3.11/site-packages/keras/src/backend.py:5727: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


1875/1875 [==============================] - 2s 1ms/step - loss: 0.2942 - accuracy: 0.9146
Epoch 2/5
1875/1875 [==============================] - 1s 797us/step - loss: 0.1418 - accuracy: 0.9576
Epoch 3/5
1875/1875 [==============================] - 1s 750us/step - loss: 0.1060 - accuracy: 0.9679
Epoch 4/5
1875/1875 [==============================] - 2s 907us/step - loss: 0.0861 - accuracy: 0.9739
Epoch 5/5
1875/1875 [==============================] - 1s 762us/step - loss: 0.0735 - accuracy: 0.9777


In [16]:
model.evaluate(x_test,y_test,verbose=2)

313/313 - 0s - loss: 0.0739 - accuracy: 0.9772 - 201ms/epoch - 641us/step


/Users/choejong-gyu/anaconda3/lib/python3.11/site-packages/keras/src/backend.py:5727: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


[0.07393351197242737, 0.9771999716758728]

In [17]:
probaility_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [18]:
probaility_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.08533704, 0.08533704, 0.08533709, 0.08533888, 0.08533704,
        0.08533704, 0.08533704, 0.23196469, 0.08533704, 0.08533712],
       [0.08533741, 0.08534061, 0.23195861, 0.08533823, 0.08533741,
        0.08533781, 0.08533742, 0.08533741, 0.08533762, 0.08533741],
       [0.08536405, 0.23153785, 0.08537923, 0.08536854, 0.08536801,
        0.08536446, 0.0853654 , 0.08547348, 0.08541477, 0.08536418],
       [0.23191708, 0.08534026, 0.08535235, 0.08534038, 0.08534016,
        0.0853448 , 0.08534015, 0.0853438 , 0.08534005, 0.08534098],
       [0.08540208, 0.08540204, 0.08540234, 0.08540205, 0.23093255,
        0.08540206, 0.08540208, 0.08540361, 0.08540241, 0.08584878]],
      dtype=float32)>