In [25]:
import tensorflow as tf
import numpy as np

In [4]:
텐서 = tf.constant([3,4,5])
print(텐서)

tf.Tensor([3 4 5], shape=(3,), dtype=int32)


In [ ]:
# x1 x2 x3의 인풋
# w1 w2 w3
# x1w1 + x2w2 + x3w3

In [5]:
텐서 = tf.constant([3,4,5])
텐서2 = tf.constant([6,7,8])
print(텐서 + 텐서2)

tf.Tensor([ 9 11 13], shape=(3,), dtype=int32)


In [19]:
텐서 = tf.constant([3,4,5])
텐서2 = tf.constant([6,7,8])
텐서3 = tf.constant([[1,2,3],
                    [3,4,5]]) # 행렬 사각형 모양으로

print(tf.add(텐서,텐서2))
print(tf.subtract(텐서,텐서2))
print(tf.divide(텐서,텐서2))
print(tf.multiply(텐서,텐서2))

tf.Tensor([ 9 11 13], shape=(3,), dtype=int32)
tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
tf.Tensor([0.5        0.57142857 0.625     ], shape=(3,), dtype=float64)
tf.Tensor([18 28 40], shape=(3,), dtype=int32)


In [12]:
텐서4 = tf.zeros(10)
print(텐서4)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)


In [13]:
텐서4 = tf.zeros([2,2]) # 2행 2열을 0으로 채우기
print(텐서4)

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)


In [14]:
텐서5 = tf.zeros([2,2,3]) # 3개를 두줄 만들고 그걸 두개로 만드는
print(텐서5)


tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]], shape=(2, 2, 3), dtype=float32)


In [20]:
print(텐서.shape) # 3개의 데이터
print(텐서3.shape) # 3개가 있는 리스트가 두개가 있음 (뒤에서부터 해석)

(3,)
(2, 3)


In [22]:
print(텐서)

tf.Tensor([3 4 5], shape=(3,), dtype=int32)


In [26]:
w = tf.Variable(1.0) # variable = 가중치
print(w.numpy())

1.0


In [27]:
w.assign(2) # 변수값 수정

print(w)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.0>
